spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#spring.datasource.url: jdbc:mysql://localhost:3306/diplomaDB?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/diplomaDB}
spring.datasource.username: root
spring.datasource.password: 1410

spring.jpa.show-sql: true
#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
#properties.hibernate.dialect: org.hibernate.dialect.MySQL7Dialect
properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
server.port: ${PORT:8081}
#server:
#  port: 8081
spring.jpa.hibernate.ddl-auto: none

blog.title: DevPub
blog.subtitle: Devs' stories
blog.phone: +7-903-1368108
blog.email: dude1410@mail.ru
blog.copyright: Vladysik Pavel
blog.copyrightFrom: 2021